spring:
  datasource:
    url: jdbc:mysql://47.98.150.219:3306/zzh-system?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    password: 123456
    host: 127.0.0.1
    port: 6379
  redisson:
    file: classpath:redisson.yml
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.example.demo.mapper: debug
#management:
#  endpoints:
#    enabled-by-default: false
#  endpoint:
#    info:
#      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 7777

#security:
#  oauth2:
#    client:
#      client-id: test
#      client-secret: test
#      registered-redirect-uri: http://mrbird.cc
